### ISSUE TITLE
Multi-Architecture Support for ARM64 in Docker Image?

### ISSUE THREAD

**Issue by MartMet** [itobey/fddb-exporter#34]
Hi,

First off, great work, and thank you!

I attempted to run your Docker image/Helm chart on an ARM64 server, but encountered the following error:

`exec /__cacert_entrypoint.sh: exec format error`

Would it be possible to add multi-architecture support, including ARM64, to the Docker image?

**Comment by itobey** [comment]
Hi,

I'm glad you like it! Yes of course! I actually just released version 1.2.2 as an ARM64 image:
`docker pull ghcr.io/itobey/fddb-exporter:1.2.2`

ARM64 support has been on the roadmap anyway (see README.md) and your inquiry just pushed me to do it now. :)
Let me know what you think. Would you also be interested in a Flutter app as a frontend for the exporter? I'm developing one for myself, but I think I can open source it as well.

**Comment by MartMet** [comment]
Thanks for the quick response! I tested it, and it works perfectly on ARM64 :)

For my use case, a Flutter app would be a bit too much, but I appreciate the suggestion. Would you mind sharing a template for your Grafana dashboard?

**Comment by MartMet** [comment]
Ah, I understand. 
If I may suggest an alternative database, InfluxDB could be a good option—it's one I personally use alongside Grafana. However, since InfluxDB is a pure time-series database, it might not be ideal for capturing detailed information about daily products.

**Comment by itobey** [comment]
I figured a document oriented database like MongoDB to be the best for storing the daily products. However I was unaware MongoDB cannot be a datasource in a selfhosted Grafana instance. As I am personally using InfluxDB as well, I might integrate it in the future, if there is no appropriate way to connect MongoDB to Grafana (I'll do a bit of research prior to this). Maybe I'll have MongoDB as implemented currently and InfluxDB as an extra optional setting, so only the total values of a day (calories, fat, etc.) are exported to InfluxDB, which will then be used in Grafana.

**Comment by itobey** [comment]
I've added InfluxDB in version 1.5.0 of the app. Please try it out :)

**Comment by MartMet** [comment]
Thanks a lot, i will give it a try. :)
